kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi