kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sabnzbd.download_pvc_size }}